### ISSUE TITLE
Sync observations stopped working

### ISSUE THREAD

**Issue by dominictinner** [rcloran/lr-inaturalist-publish#7]
If i try to full sync my observations, this error pops up:
[string "SyncObservations.lua"]:273: attempt to index field '?' (a nil value)

The unidentified observation (https://www.inaturalist.org/observations/164270315) assumed to trigger the error has now been identified, but the problem remains.

How can I download the log files? In the plugin manager, the button to download log files is greyed out. I use iNaturalist Publish Plugin, v0.5.0.

**Comment by rcloran** [comment]
Link to original report: https://github.com/rcloran/lr-inaturalist-publish/discussions/6#discussioncomment-6031942

It looks like the error message is now different to what you originally reported, so I think that adding the identification to the observation maybe did change something (uncovering a second issue, probably).

I've just written a wiki page that explains the log file location and how to create debug logs: https://github.com/rcloran/lr-inaturalist-publish/wiki/Logging . If it's not clear please let me know (I wrote it in a rush, so my apologies if it's not easy to understand).

**Comment by rcloran** [comment]
Do you have "Update keywords from iNaturalist data" turned on?

**Comment by rcloran** [comment]
I've managed to recreate this with my own observations -- no need to upload logs!

**Comment by rcloran** [comment]
v0.5.1 should fix this (and the first problem you ran into where an observation with no identifications caused a sync failure). Please re-open the issue if the same problem still happens.

[ab67dbde536f2736201c87a3ecb438a754ef7739](https://github.com/rcloran/lr-inaturalist-publish/commit/ab67dbde536f2736201c87a3ecb438a754ef7739)

**Comment by dominictinner** [comment]
I can confirm that it works perfectly again. Thank you so much for the quick fix!
